sudo: required

language: minimal

dist: trusty

services:
  - docker

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
  - echo "No tests to perform"
deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
